
//---------------------------------"
// This file is generated by make."
// Any changes will be lost!"
//---------------------------------"

#define TOOLSET_SHORT	"WIT"
#define TOOLSET_LONG	"Wiimms ISO Tools"
#define WIT_SHORT	"wit"
#define WIT_LONG	"Wiimms ISO Tool"
#define WWT_SHORT	"wwt"
#define WWT_LONG	"Wiimms WBFS Tool"
#define WDF_SHORT	"wdf"
#define WDF_LONG	"Wiimms WDF Tool"
#define WFUSE_SHORT	"wfuse"
#define WFUSE_LONG	"Wiimms FUSE Tool"
#define AUTHOR		"Dirk Clemens"

#define VERSION		"2.10a"
#define VERSION_NUM	"2.10a"
#define BETA_VERSION	0

#define REVISION	""
#define REVISION_NUM	4119
#define REVISION_NEXT	

#define BINTIME		1349988716
#define DATE		"2012-10-11"
#define TIME		"22:51:56"
#define DATETIME	"2012-10-11 22:51:56"

#define INSTALL_PATH	"/usr/local"
#define SHARE_PATH	"/usr/local/share/wit"
#define WIN_INSTALL_PATH "Wiimm/WIT"

#define URI_REPOS	"http://opensvn.wiimm.de/wii/trunk/wiimms-iso-tools//"
#define URI_VIEWVC	"http://wit.wiimm.de/r/viewvc/"
#define URI_HOME	"http://wit.wiimm.de/"
#define URI_DOWNLOAD	"http://wit.wiimm.de/download"

